### ISSUE TITLE
Get data manager dlme-transform permissions

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#135]
As the DLME data manager, I need to run airflow DAGs end to end locally. Currently the transform task fails with:
```
[2022-05-12, 16:43:35 UTC] {base_aws.py:431} WARNING - Unable to use Airflow Connection for credentials.
[2022-05-12, 16:43:35 UTC] {credentials.py:1120} INFO - Found credentials in environment variables.
[2022-05-12, 16:43:35 UTC] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 291, in execute
    self._start_task(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 351, in _start_task
    response = self.client.run_task(**run_opts)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 745, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the RunTask operation: User: arn:aws:iam::390882271260:user/jtim is not authorized to perform: ecs:RunTask on resource: arn:aws:ecs:us-west-2:390882271260:task-definition/dlme-transform with an explicit deny in a service control policy
[2022-05-12, 16:43:36 UTC] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=ifpo, task_id=IFPO_ETL.photographs_etl.transform_ifpo.photographs, execution_date=20220512T163658, start_date=20220512T164335, end_date=20220512T164336
[2022-05-12, 16:43:36 UTC] {standard_task_runner.py:89} ERROR - Failed to execute job 1738 for task IFPO_ETL.photographs_etl.transform_ifpo.photographs
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 291, in execute
    self._start_task(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 351, in _start_task
    response = self.client.run_task(**run_opts)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 745, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the RunTask operation: User: arn:aws:iam::390882271260:user/jtim is not authorized to perform: ecs:RunTask on resource: arn:aws:ecs:us-west-2:390882271260:task-definition/dlme-transform with an explicit deny in a service control policy
[2022-05-12, 16:43:36 UTC] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-12, 16:43:36 UTC] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by aaron-collier** [comment]
@jacobthill I'm going to close this issue as we've added some documentation that may help. We can walk through it if necessary.
