### ISSUE TITLE
Yale harvest fails with 500 error

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme-airflow#152]
```
[2022-07-26, 22:00:49 UTC] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/implementations/http.py", line 391, in _info
    await _file_info(
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/implementations/http.py", line 772, in _file_info
    r.raise_for_status()
  File "/home/airflow/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('[https://collections.peabody.yale.edu/search/Search/Results?join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=BC&type0%5B%5D=AllFields&limit=100&page=5&filter%5B%5D=~collection:%22Anthropology%22&filter%5B%5D=resource:%22Resource+available+online%22&view=csv')](https://collections.peabody.yale.edu/search/Search/Results?join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=BC&type0%5B%5D=AllFields&limit=100&page=5&filter%5B%5D=~collection:%22Anthropology%22&filter%5B%5D=resource:%22Resource+available+online%22&view=csv%27))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dlme_airflow/harvester/source_harvester.py", line 38, in data_source_harvester
    dataframe_to_file(source, kwargs[PROVIDER], kwargs.get(COLLECTION, None))
  File "/opt/airflow/dlme_airflow/utils/dataframe.py", line 38, in dataframe_to_file
    source_df = dataframe.read().drop_duplicates(subset=[unique_id], keep="first")
  File "/home/airflow/.local/lib/python3.9/site-packages/intake/source/csv.py", line 130, in read
    return self._dataframe.compute()
  File "/home/airflow/.local/lib/python3.9/site-packages/dask/base.py", line 314, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/dask/base.py", line 602, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/dask/threaded.py", line 89, in get
    results = get_async(
  File "/home/airflow/.local/lib/python3.9/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/home/airflow/.local/lib/python3.9/site-packages/dask/local.py", line 319, in reraise
    raise exc
  File "/home/airflow/.local/lib/python3.9/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/home/airflow/.local/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/airflow/.local/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/airflow/.local/lib/python3.9/site-packages/dask/core.py", line 113, in _execute_task
    return [_execute_task(a, cache) for a in arg]
  File "/home/airflow/.local/lib/python3.9/site-packages/dask/core.py", line 113, in <listcomp>
    return [_execute_task(a, cache) for a in arg]
  File "/home/airflow/.local/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/airflow/.local/lib/python3.9/site-packages/dask/bytes/core.py", line 189, in read_block_from_file
    with copy.copy(lazy_file) as f:
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/core.py", line 104, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/spec.py", line 1037, in open
    f = self._open(
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/implementations/http.py", line 340, in _open
    size = size or self.info(path, **kwargs)["size"]
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 86, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 66, in sync
    raise return_result
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 26, in _runner
    result[0] = await coro
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/implementations/http.py", line 404, in _info
    raise FileNotFoundError(url) from exc
FileNotFoundError: https://collections.peabody.yale.edu/search/Search/Results?join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=BC&type0%5B%5D=AllFields&limit=100&page=5&filter%5B%5D=~collection%3A%22Anthropology%22&filter%5B%5D=resource%3A%22Resource+available+online%22&view=csv
[2022-07-26, 22:00:49 UTC] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=yale, task_id=YALE_ETL.babylon_etl.yale_babylon_harvest, execution_date=20220726T214250, start_date=20220726T215535, end_date=20220726T220049
[2022-07-26, 22:00:49 UTC] {standard_task_runner.py:92} ERROR - Failed to execute job 27 for task YALE_ETL.babylon_etl.yale_babylon_harvest (https://collections.peabody.yale.edu/search/Search/Results?join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=BC&type0%5B%5D=AllFields&limit=100&page=5&filter%5B%5D=~collection%3A%22Anthropology%22&filter%5B%5D=resource%3A%22Resource+available+online%22&view=csv; 69310)
[2022-07-26, 22:00:50 UTC] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26, 22:00:50 UTC] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by aaron-collier** [comment]
@jacobthill this is a reproducible but odd situation that I think warrants some discussion and possibly contacting Yale if we can't resolve locally. I will add it to our next PO/TL check in.

**Comment by edsu** [comment]
These 500 errors seem intermittent, since I've tried the exact URL that failed again with `wget` and it downloaded just fine. Perhaps we could have some optional retry behavior with a sleep for some providers? We wouldn't want it to get stuck in an infinite loop retrying on things that consistently return a 500 error.

**Comment by edsu** [comment]
Here's a simple way to trigger the exception outside of Airflow:
```python
import intake

cat = intake.open_catalog('catalogs/yale.yaml')
df = cat.babylonian.read()
```

**Comment by edsu** [comment]
I'm noticing that underneath *intake* uses *dask* for reading the CSVs [IN PARALLEL(https://docs.dask.org/en/stable/generated/dask.dataframe.read_csv.html?#dask.dataframe.read_csv)! So those CSV files downloads are being hit all at once, which might be a factor for why they are throwing a `500` error.

**Comment by edsu** [comment]
Before I get into creating a new driver that loads the CSVs sequentially I thought I would check in over on the dask forum to see if there was an option to control the parallelization. I didn't see anything when I looked at the code, but it was relatively complicated so I might have missed something.

https://dask.discourse.group/t/sequential-reading-of-csvs/1059

**Comment by edsu** [comment]
In trying to understand better what Dask does (used by Intake) to load multiple CSVs I set up a bunch of CSV files on a webserver I controlled, and requested a bunch of URLs:

```python
﻿import dask.dataframe

urls = [
      "https://inkdroid.org/tmp/yale/1.csv",
      "https://inkdroid.org/tmp/yale/2.csv",
      "https://inkdroid.org/tmp/yale/3.csv",
      "https://inkdroid.org/tmp/yale/4.csv",
      "https://inkdroid.org/tmp/yale/5.csv",
      "https://inkdroid.org/tmp/yale/6.csv",
      "https://inkdroid.org/tmp/yale/7.csv",
      "https://inkdroid.org/tmp/yale/8.csv",
      "https://inkdroid.org/tmp/yale/9.csv",
      "https://inkdroid.org/tmp/yale/10.csv",
      "https://inkdroid.org/tmp/yale/11.csv",
      "https://inkdroid.org/tmp/yale/12.csv",
      "https://inkdroid.org/tmp/yale/13.csv",
      "https://inkdroid.org/tmp/yale/14.csv",
      "https://inkdroid.org/tmp/yale/15.csv",
      "https://inkdroid.org/tmp/yale/16.csv",
﻿      "https://inkdroid.org/tmp/yale/17.csv",
      "https://inkdroid.org/tmp/yale/18.csv",
      "https://inkdroid.org/tmp/yale/19.csv",
      "https://inkdroid.org/tmp/yale/20.csv"
  ]

df = dask.dataframe.read_csv(urlpath=urls)
print(len(df))
```

The interesting thing I learned is that it starts by doing a bunch of concurrent HEAD requests of the data source to see how big the files are and what HTTP methods the resource supports:

```
173.73.44.210 - - [29/Aug/2022:14:32:33 +0000] "HEAD /tmp/yale/1.csv HTTP/1.1" 200 5080 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:34 +0000] "HEAD /tmp/yale/2.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:34 +0000] "HEAD /tmp/yale/3.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:34 +0000] "HEAD /tmp/yale/4.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:34 +0000] "HEAD /tmp/yale/5.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:34 +0000] "HEAD /tmp/yale/6.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:34 +0000] "HEAD /tmp/yale/7.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:34 +0000] "HEAD /tmp/yale/8.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:34 +0000] "HEAD /tmp/yale/9.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:34 +0000] "HEAD /tmp/yale/10.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:34 +0000] "HEAD /tmp/yale/11.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:34 +0000] "HEAD /tmp/yale/12.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:35 +0000] "HEAD /tmp/yale/13.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:35 +0000] "HEAD /tmp/yale/14.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:35 +0000] "HEAD /tmp/yale/15.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:35 +0000] "HEAD /tmp/yale/16.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:35 +0000] "HEAD /tmp/yale/17.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:35 +0000] "HEAD /tmp/yale/18.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:35 +0000] "HEAD /tmp/yale/19.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:35 +0000] "HEAD /tmp/yale/20.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:35 +0000] "HEAD /tmp/yale/1.csv HTTP/1.1" 200 334 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:35 +0000] "GET /tmp/yale/1.csv HTTP/1.1" 206 4489870 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:36 +0000] "HEAD /tmp/yale/1.csv HTTP/1.1" 200 334 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:37 +0000] "HEAD /tmp/yale/4.csv HTTP/1.1" 200 5082 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:37 +0000] "HEAD /tmp/yale/5.csv HTTP/1.1" 200 5082 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:37 +0000] "HEAD /tmp/yale/3.csv HTTP/1.1" 200 5082 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:37 +0000] "HEAD /tmp/yale/2.csv HTTP/1.1" 200 5082 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:36 +0000] "GET /tmp/yale/1.csv HTTP/1.1" 206 4489870 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:38 +0000] "HEAD /tmp/yale/6.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:37 +0000] "GET /tmp/yale/5.csv HTTP/1.1" 206 89782772 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:38 +0000] "GET /tmp/yale/6.csv HTTP/1.1" 206 89782772 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:33:02 +0000] "HEAD /tmp/yale/7.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:33:02 +0000] "HEAD /tmp/yale/8.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:33:02 +0000] "GET /tmp/yale/7.csv HTTP/1.1" 206 89782772 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:33:22 +0000] "HEAD /tmp/yale/9.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:37 +0000] "GET /tmp/yale/4.csv HTTP/1.1" 206 89782772 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:33:38 +0000] "HEAD /tmp/yale/10.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:33:03 +0000] "GET /tmp/yale/8.csv HTTP/1.1" 206 89782772 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:33:44 +0000] "HEAD /tmp/yale/11.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:33:22 +0000] "GET /tmp/yale/9.csv HTTP/1.1" 206 89782772 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:33:50 +0000] "HEAD /tmp/yale/12.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:37 +0000] "GET /tmp/yale/2.csv HTTP/1.1" 206 89782772 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:34:06 +0000] "HEAD /tmp/yale/13.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:32:37 +0000] "GET /tmp/yale/3.csv HTTP/1.1" 206 89782772 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:34:13 +0000] "HEAD /tmp/yale/14.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:33:50 +0000] "GET /tmp/yale/12.csv HTTP/1.1" 206 89782772 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:34:14 +0000] "HEAD /tmp/yale/15.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:33:44 +0000] "GET /tmp/yale/11.csv HTTP/1.1" 206 89782772 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:33:38 +0000] "GET /tmp/yale/10.csv HTTP/1.1" 206 89782772 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:34:23 +0000] "HEAD /tmp/yale/16.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:34:23 +0000] "HEAD /tmp/yale/17.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:34:14 +0000] "GET /tmp/yale/15.csv HTTP/1.1" 206 89782772 "-" "Python/3.10 aiohttp/3.8.1"
173.73.44.210 - - [29/Aug/2022:14:34:43 +0000] "HEAD /tmp/yale/18.csv HTTP/1.1" 200 336 "-" "Python/3.10 aiohttp/3.8.1"
```

Unfortunately the Yale server appears to be generating this data dynamically in response to the HEAD requests:

```
➜  ~ time curl -I https://collections.peabody.yale.edu/search/Search/Results\?join\=AND\&bool0%5B%5D\=AND\&lookfor0%5B%5D\=BC\&type0%5B%5D\=AllFields\&limit\=100\&page\=5\&filter%5B%5D\=\~collection%3A%22Anthropology%22\&filter%5B%5D\=resource%3A%22Resource+available+online%22\&view\=csv
HTTP/1.1 200 OK
Date: Mon, 29 Aug 2022 15:25:27 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.6.40
X-Powered-By: PHP/5.6.40
Set-Cookie: PHPSESSID=spqkmebf2rsuchctd4e337lcf3; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: ui=standard; path=/
Content-Disposition: attachment; filename=record.csv
Content-Type: text/csv;charset=UTF-8

curl -I   0.02s user 0.01s system 0% cpu 5.834 total
```

I couldn't figure out a way to control this behavior, so I think we'll need a custom driver.
