### ISSUE TITLE
CSIC Fails (OAI)

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme-airflow#163]
```[2022-08-16, 21:08:10 UTC] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dlme_airflow/harvester/source_harvester.py", line 17, in data_source_harvester
    dataframe_to_file(collection)
  File "/opt/airflow/dlme_airflow/utils/dataframe.py", line 35, in dataframe_to_file
    source_df = collection.catalog.read().drop_duplicates(
  File "/opt/airflow/dlme_airflow/drivers/oai_xml.py", line 110, in read
    self._load_metadata()
  File "/home/airflow/.local/lib/python3.9/site-packages/intake/source/base.py", line 236, in _load_metadata
    self._schema = self._get_schema()
  File "/opt/airflow/dlme_airflow/drivers/oai_xml.py", line 99, in _get_schema
    self._open_set()
  File "/opt/airflow/dlme_airflow/drivers/oai_xml.py", line 33, in _open_set
    record.update(self._from_metadata(xtree))
  File "/opt/airflow/dlme_airflow/drivers/oai_xml.py", line 69, in _from_metadata
    oai_block = manifest.xpath("//oai_dc:dc", namespaces=NS)[
IndexError: list index out of range
[2022-08-16, 21:08:11 UTC] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=csic, task_id=CSIC_ETL.manuscripts_etl.csic_manuscripts_harvest, execution_date=20220816T210739, start_date=20220816T210805, end_date=20220816T210811
[2022-08-16, 21:08:11 UTC] {standard_task_runner.py:92} ERROR - Failed to execute job 222 for task CSIC_ETL.manuscripts_etl.csic_manuscripts_harvest (list index out of range; 5850)
```

**Comment by aaron-collier** [comment]
Closed by #203
