### ISSUE TITLE
Princeton ymdi IIIF harvest fails: 'list' object has no attribute 'strip'

### ISSUE THREAD

**Issue by edsu** [sul-dlss/dlme-airflow#226]
I happened to notice this error from the Princeton ymdi collection, which uses the IIIF driver:

```
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dlme_airflow/harvester/source_harvester.py", line 17, in data_source_harvester
    dataframe_to_file(collection)
  File "/opt/airflow/dlme_airflow/utils/dataframe.py", line 35, in dataframe_to_file
    source_df = collection.catalog.read().drop_duplicates(
  File "/opt/airflow/dlme_airflow/drivers/iiif_json.py", line 113, in read
    df = pd.concat([self.read_partition(i) for i in range(self.npartitions)])
  File "/opt/airflow/dlme_airflow/drivers/iiif_json.py", line 113, in <listcomp>
    df = pd.concat([self.read_partition(i) for i in range(self.npartitions)])
  File "/home/airflow/.local/lib/python3.9/site-packages/intake/source/base.py", line 377, in read_partition
    return self._get_partition(i)
  File "/opt/airflow/dlme_airflow/drivers/iiif_json.py", line 84, in _get_partition
    result = self._open_manifest(self._manifest_urls[i])
  File "/opt/airflow/dlme_airflow/drivers/iiif_json.py", line 31, in _open_manifest
    record = self._construct_fields(manifest_detail)
  File "/opt/airflow/dlme_airflow/drivers/iiif_json.py", line 49, in _construct_fields
    output[name] = result[0].strip()
AttributeError: 'list' object has no attribute 'strip'
```

**Comment by jmartin-sul** [comment]
so, i tried to reproduce this, but i think i may have fixed it in https://github.com/sul-dlss/dlme-airflow/pull/218

i can reproduce the problem using the commit before that (c34161dce07b18fa178a257ab97b92842615c4d0), and using the last commit where there was a `strip` call on line 49 of `_construct_fields` in `iiif_json.py` (706a713b4f584648cd9a14c1771a3c1566ad2a22), but i can't reproduce on current `main`.

do you know whether you were on the latest `main` when you ran into this / can you still reproduce it on the latest `main`?
