### ISSUE TITLE
Princeton manuscripts failing harvest

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#251]
Not sure what the issue is. It seems like a json decoding error but the url leads to a valid json document. This might be related to some larger performance issue. It looks like `None` is being returned and we are trying to parse it as json. Maybe `None` was returned because the AWS worker was overloaded or something similar?

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/dlme_airflow/harvester/source_harvester.py", line 17, in data_source_harvester
    dataframe_to_file(collection)
  File "/home/airflow/.local/lib/python3.9/site-packages/dlme_airflow/utils/dataframe.py", line 36, in dataframe_to_file
    source_df = collection.catalog.read().drop_duplicates(
  File "/home/airflow/.local/lib/python3.9/site-packages/dlme_airflow/drivers/iiif_json.py", line 121, in read
    df = pd.concat([self.read_partition(i) for i in range(self.npartitions)])
  File "/home/airflow/.local/lib/python3.9/site-packages/dlme_airflow/drivers/iiif_json.py", line 121, in <listcomp>
    df = pd.concat([self.read_partition(i) for i in range(self.npartitions)])
  File "/home/airflow/.local/lib/python3.9/site-packages/intake/source/base.py", line 377, in read_partition
    return self._get_partition(i)
  File "/home/airflow/.local/lib/python3.9/site-packages/dlme_airflow/drivers/iiif_json.py", line 92, in _get_partition
    result = self._open_manifest(self._manifest_urls[i])
  File "/home/airflow/.local/lib/python3.9/site-packages/dlme_airflow/drivers/iiif_json.py", line 30, in _open_manifest
    manifest_result = requests.get(manifest_url).json()
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by edsu** [comment]
I think we probably want to check the response object (to make sure it's a 200 OK) before calling the `.json()` method on it here?

https://github.com/sul-dlss/dlme-airflow/blob/main/dlme_airflow/drivers/iiif_json.py#L25

**Comment by edsu** [comment]
Yeah, this is the result of one of the Manifest URLs in their Collection returning a 404. I guess we should skip these right?

```
$ curl -i https://figgy.princeton.edu/concern/scanned_resources/e6977a4b-edd4-4aa6-bcb0-c605a82d2721/manifest
HTTP/2 404
server: nginx/1.21.6
date: Wed, 21 Sep 2022 19:19:37 GMT
content-type: application/json
status: 404 Not Found
cache-control: no-cache
strict-transport-security: max-age=63072000; includeSubDomains
referrer-policy: strict-origin-when-cross-origin
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block
x-request-id: e4cc984b-5701-4166-beed-8f1734049c18
x-download-options: noopen
x-runtime: 0.475674
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
x-powered-by: Phusion Passenger(R) 6.0.15
access-control-allow-credentials: true
access-control-allow-methods: GET, POST, OPTIONS
access-control-allow-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Origin
vary: Origin
```

**Comment by jacobthill** [comment]
Yes skipping makes sense and maybe logging it
