### ISSUE TITLE
Empty string causing oai_xml driver to fail

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#263]
The DASI objects collections fails harvest with the following error:

```*** Reading remote log from s3://dlme-airflow-task-logs-dev/dag_id=dasi/run_id=scheduled__2022-09-22T16:40:00+00:00/task_id=DASI_ETL.objects_etl.dasi_objects_harvest/attempt=1.log.
[2022-09-23, 16:45:32 UTC] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dasi.DASI_ETL.objects_etl.dasi_objects_harvest scheduled__2022-09-22T16:40:00+00:00 [queued]>
[2022-09-23, 16:45:32 UTC] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dasi.DASI_ETL.objects_etl.dasi_objects_harvest scheduled__2022-09-22T16:40:00+00:00 [queued]>
[2022-09-23, 16:45:32 UTC] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-23, 16:45:32 UTC] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-09-23, 16:45:32 UTC] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-23, 16:45:32 UTC] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): DASI_ETL.objects_etl.dasi_objects_harvest> on 2022-09-22 16:40:00+00:00
[2022-09-23, 16:45:32 UTC] {standard_task_runner.py:52} INFO - Started process 255 to run task
[2022-09-23, 16:45:32 UTC] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dasi', 'DASI_ETL.objects_etl.dasi_objects_harvest', 'scheduled__2022-09-22T16:40:00+00:00', '--job-id', '2821', '--raw', '--subdir', 'DAGS_FOLDER/harvest_catalog.py', '--cfg-path', '/tmp/tmprltrxgan', '--error-file', '/tmp/tmp2anj7v57']
[2022-09-23, 16:45:32 UTC] {standard_task_runner.py:80} INFO - Job 2821: Subtask DASI_ETL.objects_etl.dasi_objects_harvest
[2022-09-23, 16:45:32 UTC] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/configuration.py:528: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-09-23, 16:45:32 UTC] {task_command.py:371} INFO - Running <TaskInstance: dasi.DASI_ETL.objects_etl.dasi_objects_harvest scheduled__2022-09-22T16:40:00+00:00 [running]> on host ip-10-0-65-39.us-west-2.compute.internal
[2022-09-23, 16:45:33 UTC] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jtim@stanford.edu, amcollie@stanford.edu
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dasi
AIRFLOW_CTX_TASK_ID=DASI_ETL.objects_etl.dasi_objects_harvest
AIRFLOW_CTX_EXECUTION_DATE=2022-09-22T16:40:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-22T16:40:00+00:00
[2022-09-23, 16:45:39 UTC] {oai_xml.py:55} INFO - 100
[2022-09-23, 16:45:44 UTC] {oai_xml.py:55} INFO - 200
[2022-09-23, 16:45:50 UTC] {oai_xml.py:55} INFO - 300
[2022-09-23, 16:45:55 UTC] {oai_xml.py:55} INFO - 400
[2022-09-23, 16:46:00 UTC] {oai_xml.py:55} INFO - 500
[2022-09-23, 16:46:06 UTC] {oai_xml.py:55} INFO - 600
[2022-09-23, 16:46:16 UTC] {oai_xml.py:55} INFO - 700
[2022-09-23, 16:46:23 UTC] {oai_xml.py:55} INFO - 800
[2022-09-23, 16:46:29 UTC] {oai_xml.py:55} INFO - 900
[2022-09-23, 16:46:35 UTC] {oai_xml.py:55} INFO - 1000
[2022-09-23, 16:46:40 UTC] {oai_xml.py:55} INFO - 1100
[2022-09-23, 16:46:46 UTC] {oai_xml.py:55} INFO - 1200
[2022-09-23, 16:46:51 UTC] {oai_xml.py:55} INFO - 1300
[2022-09-23, 16:46:56 UTC] {oai_xml.py:55} INFO - 1400
[2022-09-23, 16:47:02 UTC] {oai_xml.py:55} INFO - 1500
[2022-09-23, 16:47:07 UTC] {oai_xml.py:55} INFO - 1600
[2022-09-23, 16:47:12 UTC] {oai_xml.py:55} INFO - 1700
[2022-09-23, 16:47:18 UTC] {oai_xml.py:55} INFO - 1800
[2022-09-23, 16:47:27 UTC] {oai_xml.py:55} INFO - 1900
[2022-09-23, 16:47:33 UTC] {oai_xml.py:55} INFO - 2000
[2022-09-23, 16:47:38 UTC] {oai_xml.py:55} INFO - 2100
[2022-09-23, 16:47:44 UTC] {oai_xml.py:55} INFO - 2200
[2022-09-23, 16:47:49 UTC] {oai_xml.py:55} INFO - 2300
[2022-09-23, 16:47:54 UTC] {oai_xml.py:55} INFO - 2400
[2022-09-23, 16:48:00 UTC] {oai_xml.py:55} INFO - 2500
[2022-09-23, 16:48:05 UTC] {oai_xml.py:55} INFO - 2600
[2022-09-23, 16:48:11 UTC] {oai_xml.py:55} INFO - 2700
[2022-09-23, 16:48:16 UTC] {oai_xml.py:55} INFO - 2800
[2022-09-23, 16:48:21 UTC] {oai_xml.py:55} INFO - 2900
[2022-09-23, 16:48:27 UTC] {oai_xml.py:55} INFO - 3000
[2022-09-23, 16:48:32 UTC] {oai_xml.py:55} INFO - 3100
[2022-09-23, 16:48:37 UTC] {oai_xml.py:55} INFO - 3200
[2022-09-23, 16:48:43 UTC] {oai_xml.py:55} INFO - 3300
[2022-09-23, 16:48:48 UTC] {oai_xml.py:55} INFO - 3400
[2022-09-23, 16:48:54 UTC] {oai_xml.py:55} INFO - 3500
[2022-09-23, 16:48:59 UTC] {oai_xml.py:55} INFO - 3600
[2022-09-23, 16:49:05 UTC] {oai_xml.py:55} INFO - 3700
[2022-09-23, 16:49:10 UTC] {oai_xml.py:55} INFO - 3800
[2022-09-23, 16:49:15 UTC] {oai_xml.py:55} INFO - 3900
[2022-09-23, 16:49:20 UTC] {oai_xml.py:55} INFO - 4000
[2022-09-23, 16:49:25 UTC] {oai_xml.py:55} INFO - 4100
[2022-09-23, 16:49:31 UTC] {oai_xml.py:55} INFO - 4200
[2022-09-23, 16:49:36 UTC] {oai_xml.py:55} INFO - 4300
[2022-09-23, 16:49:41 UTC] {oai_xml.py:55} INFO - 4400
[2022-09-23, 16:49:46 UTC] {oai_xml.py:55} INFO - 4500
[2022-09-23, 16:49:51 UTC] {oai_xml.py:55} INFO - 4600
[2022-09-23, 16:49:57 UTC] {oai_xml.py:55} INFO - 4700
[2022-09-23, 16:50:02 UTC] {oai_xml.py:55} INFO - 4800
[2022-09-23, 16:50:12 UTC] {oai_xml.py:55} INFO - 4900
[2022-09-23, 16:50:18 UTC] {oai_xml.py:55} INFO - 5000
[2022-09-23, 16:50:23 UTC] {oai_xml.py:55} INFO - 5100
[2022-09-23, 16:50:29 UTC] {oai_xml.py:55} INFO - 5200
[2022-09-23, 16:50:34 UTC] {oai_xml.py:55} INFO - 5300
[2022-09-23, 16:50:39 UTC] {oai_xml.py:55} INFO - 5400
[2022-09-23, 16:50:44 UTC] {oai_xml.py:55} INFO - 5500
[2022-09-23, 16:50:49 UTC] {oai_xml.py:55} INFO - 5600
[2022-09-23, 16:50:54 UTC] {oai_xml.py:55} INFO - 5700
[2022-09-23, 16:50:59 UTC] {oai_xml.py:55} INFO - 5800
[2022-09-23, 16:51:05 UTC] {oai_xml.py:55} INFO - 5900
[2022-09-23, 16:51:11 UTC] {oai_xml.py:55} INFO - 6000
[2022-09-23, 16:51:18 UTC] {oai_xml.py:55} INFO - 6100
[2022-09-23, 16:51:25 UTC] {oai_xml.py:55} INFO - 6200
[2022-09-23, 16:51:31 UTC] {oai_xml.py:55} INFO - 6300
[2022-09-23, 16:51:39 UTC] {oai_xml.py:55} INFO - 6400
[2022-09-23, 16:51:45 UTC] {oai_xml.py:55} INFO - 6500
[2022-09-23, 16:51:51 UTC] {oai_xml.py:55} INFO - 6600
[2022-09-23, 16:51:57 UTC] {oai_xml.py:55} INFO - 6700
[2022-09-23, 16:52:02 UTC] {oai_xml.py:55} INFO - 6800
[2022-09-23, 16:52:08 UTC] {oai_xml.py:55} INFO - 6900
[2022-09-23, 16:52:13 UTC] {oai_xml.py:55} INFO - 7000
[2022-09-23, 16:52:14 UTC] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sickle/iterator.py", line 91, in _next_response
    raise getattr(
AttributeError: module 'sickle.oaiexceptions' has no attribute 'UNKNOWN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/dlme_airflow/harvester/source_harvester.py", line 17, in data_source_harvester
    dataframe_to_file(collection)
  File "/home/airflow/.local/lib/python3.9/site-packages/dlme_airflow/utils/dataframe.py", line 36, in dataframe_to_file
    source_df = collection.catalog.read().drop_duplicates(
  File "/home/airflow/.local/lib/python3.9/site-packages/dlme_airflow/drivers/oai_xml.py", line 199, in read
    self._load_metadata()
  File "/home/airflow/.local/lib/python3.9/site-packages/intake/source/base.py", line 285, in _load_metadata
    self._schema = self._get_schema()
  File "/home/airflow/.local/lib/python3.9/site-packages/dlme_airflow/drivers/oai_xml.py", line 151, in _get_schema
    self._open_set()
  File "/home/airflow/.local/lib/python3.9/site-packages/dlme_airflow/drivers/oai_xml.py", line 52, in _open_set
    for counter, oai_record in enumerate(oai_records, start=1):
  File "/home/airflow/.local/lib/python3.9/site-packages/sickle/iterator.py", line 52, in __next__
    return self.next()
  File "/home/airflow/.local/lib/python3.9/site-packages/sickle/iterator.py", line 151, in next
    self._next_response()
  File "/home/airflow/.local/lib/python3.9/site-packages/sickle/iterator.py", line 138, in _next_response
    super(OAIItemIterator, self)._next_response()
  File "/home/airflow/.local/lib/python3.9/site-packages/sickle/iterator.py", line 94, in _next_response
    raise oaiexceptions.OAIError(description)
sickle.oaiexceptions.OAIError: Empty String at lib/dasioai.pm line 906.

[2022-09-23, 16:52:14 UTC] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=dasi, task_id=DASI_ETL.objects_etl.dasi_objects_harvest, execution_date=20220922T164000, start_date=20220923T164532, end_date=20220923T165214
[2022-09-23, 16:52:14 UTC] {standard_task_runner.py:92} ERROR - Failed to execute job 2821 for task DASI_ETL.objects_etl.dasi_objects_harvest (Empty String at lib/dasioai.pm line 906.
; 255)
[2022-09-23, 16:52:14 UTC] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-23, 16:52:14 UTC] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check```

**Comment by jacobthill** [comment]
We are currently stalled on discussions with DASI team on copyright so not working on this until those discussions are resolved.
