### ISSUE TITLE
QNL failed transform validation 

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#388]
```Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dlme_airflow/tasks/transform_validation.py", line 35, in validate_transformation
    raise Exception(
Exception: ERROR: failed to transform all harvested records: harvested record count (22535.0) != transformed record count (0)```

**Comment by jacobthill** [comment]
I started it yesterday afternoon around 1 and checked it this morning. It finished sometime in the night. It does feel like harvest is a bit more stable; we have harvested the whole collection several times now but I suspect we are still seeing transform errors since the transform results are 0
